"""Add missing fields to CommentAttachment model

Revision ID: 0349b8824f35
Revises: 5d877179a0eb
Create Date: 2025-09-24 10:22:20.729178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0349b8824f35'
down_revision: Union[str, None] = '5d877179a0eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
