"""Add advanced task features: time tracking, templates, activities, mentions, assignment history

Revision ID: 126608d4c130
Revises: 660eac970329
Create Date: 2025-09-23 03:56:09.528381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126608d4c130'
down_revision: Union[str, None] = '660eac970329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_templates_category'), 'task_templates', ['category'], unique=False)
    op.create_index(op.f('ix_task_templates_id'), 'task_templates', ['id'], unique=False)
    op.create_index(op.f('ix_task_templates_organization_id'), 'task_templates', ['organization_id'], unique=False)
    op.create_table('task_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('activity_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_activities_activity_type'), 'task_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_task_activities_created_at'), 'task_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_activities_id'), 'task_activities', ['id'], unique=False)
    op.create_index(op.f('ix_task_activities_task_id'), 'task_activities', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_activities_user_id'), 'task_activities', ['user_id'], unique=False)
    op.create_table('task_assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('previous_assignee_id', sa.Integer(), nullable=True),
    sa.Column('new_assignee_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assignment_history_assigned_by'), 'task_assignment_history', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_task_assignment_history_created_at'), 'task_assignment_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_assignment_history_id'), 'task_assignment_history', ['id'], unique=False)
    op.create_index(op.f('ix_task_assignment_history_new_assignee_id'), 'task_assignment_history', ['new_assignee_id'], unique=False)
    op.create_index(op.f('ix_task_assignment_history_previous_assignee_id'), 'task_assignment_history', ['previous_assignee_id'], unique=False)
    op.create_index(op.f('ix_task_assignment_history_task_id'), 'task_assignment_history', ['task_id'], unique=False)
    op.create_table('task_time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_time_logs_id'), 'task_time_logs', ['id'], unique=False)
    op.create_index(op.f('ix_task_time_logs_task_id'), 'task_time_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_time_logs_user_id'), 'task_time_logs', ['user_id'], unique=False)
    op.create_table('task_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('mentioning_user_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['task_comments.id'], ),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mentioning_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_mentions_comment_id'), 'task_mentions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_task_mentions_created_at'), 'task_mentions', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_mentions_id'), 'task_mentions', ['id'], unique=False)
    op.create_index(op.f('ix_task_mentions_mentioned_user_id'), 'task_mentions', ['mentioned_user_id'], unique=False)
    op.create_index(op.f('ix_task_mentions_mentioning_user_id'), 'task_mentions', ['mentioning_user_id'], unique=False)
    op.create_index(op.f('ix_task_mentions_task_id'), 'task_mentions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_mentions_task_id'), table_name='task_mentions')
    op.drop_index(op.f('ix_task_mentions_mentioning_user_id'), table_name='task_mentions')
    op.drop_index(op.f('ix_task_mentions_mentioned_user_id'), table_name='task_mentions')
    op.drop_index(op.f('ix_task_mentions_id'), table_name='task_mentions')
    op.drop_index(op.f('ix_task_mentions_created_at'), table_name='task_mentions')
    op.drop_index(op.f('ix_task_mentions_comment_id'), table_name='task_mentions')
    op.drop_table('task_mentions')
    op.drop_index(op.f('ix_task_time_logs_user_id'), table_name='task_time_logs')
    op.drop_index(op.f('ix_task_time_logs_task_id'), table_name='task_time_logs')
    op.drop_index(op.f('ix_task_time_logs_id'), table_name='task_time_logs')
    op.drop_table('task_time_logs')
    op.drop_index(op.f('ix_task_assignment_history_task_id'), table_name='task_assignment_history')
    op.drop_index(op.f('ix_task_assignment_history_previous_assignee_id'), table_name='task_assignment_history')
    op.drop_index(op.f('ix_task_assignment_history_new_assignee_id'), table_name='task_assignment_history')
    op.drop_index(op.f('ix_task_assignment_history_id'), table_name='task_assignment_history')
    op.drop_index(op.f('ix_task_assignment_history_created_at'), table_name='task_assignment_history')
    op.drop_index(op.f('ix_task_assignment_history_assigned_by'), table_name='task_assignment_history')
    op.drop_table('task_assignment_history')
    op.drop_index(op.f('ix_task_activities_user_id'), table_name='task_activities')
    op.drop_index(op.f('ix_task_activities_task_id'), table_name='task_activities')
    op.drop_index(op.f('ix_task_activities_id'), table_name='task_activities')
    op.drop_index(op.f('ix_task_activities_created_at'), table_name='task_activities')
    op.drop_index(op.f('ix_task_activities_activity_type'), table_name='task_activities')
    op.drop_table('task_activities')
    op.drop_index(op.f('ix_task_templates_organization_id'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_id'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_category'), table_name='task_templates')
    op.drop_table('task_templates')
    # ### end Alembic commands ###
