"""Add workflow automation and business rules models

Revision ID: 258cc95fcb91
Revises: 0454b7f525cc
Create Date: 2025-09-23 05:15:26.435483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258cc95fcb91'
down_revision: Union[str, None] = '0454b7f525cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_uuid', sa.String(length=36), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_type', sa.Enum('COUNT', 'SUM', 'AVERAGE', 'PERCENTAGE', 'RATIO', 'TREND', 'CUSTOM', name='metrictype'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('calculation_method', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('source_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=True),
    sa.Column('data_completeness', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'metric_name', 'entity_type', 'entity_id', 'period_start', 'period_end', name='uq_analytics_metric_period')
    )
    op.create_index(op.f('ix_analytics_metrics_calculated_at'), 'analytics_metrics', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_category'), 'analytics_metrics', ['category'], unique=False)
    op.create_index('ix_analytics_metrics_category_period', 'analytics_metrics', ['category', 'period_start', 'period_end'], unique=False)
    op.create_index('ix_analytics_metrics_entity', 'analytics_metrics', ['entity_type', 'entity_id', 'period_start'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_entity_id'), 'analytics_metrics', ['entity_id'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_entity_type'), 'analytics_metrics', ['entity_type'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_id'), 'analytics_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_is_estimated'), 'analytics_metrics', ['is_estimated'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_metric_name'), 'analytics_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_metric_type'), 'analytics_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_metric_uuid'), 'analytics_metrics', ['metric_uuid'], unique=True)
    op.create_index('ix_analytics_metrics_org_name_period', 'analytics_metrics', ['organization_id', 'metric_name', 'period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_organization_id'), 'analytics_metrics', ['organization_id'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_period_end'), 'analytics_metrics', ['period_end'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_period_start'), 'analytics_metrics', ['period_start'], unique=False)
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('trigger_conditions', sa.JSON(), nullable=False),
    sa.Column('automation_actions', sa.JSON(), nullable=False),
    sa.Column('project_ids', sa.JSON(), nullable=True),
    sa.Column('user_ids', sa.JSON(), nullable=True),
    sa.Column('task_types', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('execution_frequency', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automation_rules_active_frequency', 'automation_rules', ['is_active', 'execution_frequency'], unique=False)
    op.create_index(op.f('ix_automation_rules_id'), 'automation_rules', ['id'], unique=False)
    op.create_index(op.f('ix_automation_rules_is_active'), 'automation_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_automation_rules_name'), 'automation_rules', ['name'], unique=False)
    op.create_index('ix_automation_rules_org_type', 'automation_rules', ['organization_id', 'rule_type'], unique=False)
    op.create_index(op.f('ix_automation_rules_organization_id'), 'automation_rules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_automation_rules_rule_type'), 'automation_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_automation_rules_rule_uuid'), 'automation_rules', ['rule_uuid'], unique=True)
    op.create_table('business_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('rule_conditions', sa.JSON(), nullable=False),
    sa.Column('rule_actions', sa.JSON(), nullable=False),
    sa.Column('is_reusable', sa.Boolean(), nullable=True),
    sa.Column('is_system_rule', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_rules_category'), 'business_rules', ['category'], unique=False)
    op.create_index('ix_business_rules_category_system', 'business_rules', ['category', 'is_system_rule'], unique=False)
    op.create_index(op.f('ix_business_rules_id'), 'business_rules', ['id'], unique=False)
    op.create_index(op.f('ix_business_rules_is_system_rule'), 'business_rules', ['is_system_rule'], unique=False)
    op.create_index(op.f('ix_business_rules_name'), 'business_rules', ['name'], unique=False)
    op.create_index('ix_business_rules_org_reusable', 'business_rules', ['organization_id', 'is_reusable'], unique=False)
    op.create_index(op.f('ix_business_rules_organization_id'), 'business_rules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_business_rules_priority'), 'business_rules', ['priority'], unique=False)
    op.create_index(op.f('ix_business_rules_rule_uuid'), 'business_rules', ['rule_uuid'], unique=True)
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layout_config', sa.JSON(), nullable=False),
    sa.Column('theme_settings', sa.JSON(), nullable=True),
    sa.Column('refresh_interval', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_system_dashboard', sa.Boolean(), nullable=True),
    sa.Column('shared_with_users', sa.JSON(), nullable=True),
    sa.Column('access_permissions', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dashboards_creator_default', 'dashboards', ['created_by', 'is_default'], unique=False)
    op.create_index(op.f('ix_dashboards_dashboard_uuid'), 'dashboards', ['dashboard_uuid'], unique=True)
    op.create_index(op.f('ix_dashboards_id'), 'dashboards', ['id'], unique=False)
    op.create_index(op.f('ix_dashboards_is_default'), 'dashboards', ['is_default'], unique=False)
    op.create_index(op.f('ix_dashboards_is_public'), 'dashboards', ['is_public'], unique=False)
    op.create_index(op.f('ix_dashboards_is_system_dashboard'), 'dashboards', ['is_system_dashboard'], unique=False)
    op.create_index(op.f('ix_dashboards_name'), 'dashboards', ['name'], unique=False)
    op.create_index('ix_dashboards_org_public', 'dashboards', ['organization_id', 'is_public'], unique=False)
    op.create_index(op.f('ix_dashboards_organization_id'), 'dashboards', ['organization_id'], unique=False)
    op.create_table('report_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('threshold_operator', sa.String(length=10), nullable=False),
    sa.Column('threshold_type', sa.String(length=20), nullable=True),
    sa.Column('evaluation_window', sa.Integer(), nullable=True),
    sa.Column('consecutive_periods', sa.Integer(), nullable=True),
    sa.Column('severity_level', sa.String(length=20), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('notification_recipients', sa.JSON(), nullable=True),
    sa.Column('notification_template', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.Column('is_snoozed', sa.Boolean(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('snoozed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['snoozed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_alerts_alert_uuid'), 'report_alerts', ['alert_uuid'], unique=True)
    op.create_index(op.f('ix_report_alerts_id'), 'report_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_report_alerts_is_active'), 'report_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_report_alerts_is_snoozed'), 'report_alerts', ['is_snoozed'], unique=False)
    op.create_index(op.f('ix_report_alerts_last_evaluated_at'), 'report_alerts', ['last_evaluated_at'], unique=False)
    op.create_index(op.f('ix_report_alerts_last_triggered_at'), 'report_alerts', ['last_triggered_at'], unique=False)
    op.create_index('ix_report_alerts_metric_active', 'report_alerts', ['metric_name', 'is_active'], unique=False)
    op.create_index(op.f('ix_report_alerts_metric_name'), 'report_alerts', ['metric_name'], unique=False)
    op.create_index(op.f('ix_report_alerts_name'), 'report_alerts', ['name'], unique=False)
    op.create_index('ix_report_alerts_next_eval', 'report_alerts', ['is_active', 'last_evaluated_at'], unique=False)
    op.create_index('ix_report_alerts_org_active', 'report_alerts', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_report_alerts_organization_id'), 'report_alerts', ['organization_id'], unique=False)
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.Enum('PROJECT_OVERVIEW', 'TASK_ANALYTICS', 'TIME_TRACKING', 'USER_PRODUCTIVITY', 'TEAM_PERFORMANCE', 'RESOURCE_UTILIZATION', 'BUDGET_ANALYSIS', 'MILESTONE_TRACKING', 'CUSTOM_DASHBOARD', 'WORKFLOW_ANALYSIS', name='reporttype'), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('default_filters', sa.JSON(), nullable=True),
    sa.Column('chart_configurations', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_system_template', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_templates_id'), 'report_templates', ['id'], unique=False)
    op.create_index(op.f('ix_report_templates_is_active'), 'report_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_report_templates_is_public'), 'report_templates', ['is_public'], unique=False)
    op.create_index(op.f('ix_report_templates_is_system_template'), 'report_templates', ['is_system_template'], unique=False)
    op.create_index(op.f('ix_report_templates_name'), 'report_templates', ['name'], unique=False)
    op.create_index('ix_report_templates_org_type', 'report_templates', ['organization_id', 'report_type'], unique=False)
    op.create_index(op.f('ix_report_templates_organization_id'), 'report_templates', ['organization_id'], unique=False)
    op.create_index('ix_report_templates_public_active', 'report_templates', ['is_public', 'is_active'], unique=False)
    op.create_index(op.f('ix_report_templates_report_type'), 'report_templates', ['report_type'], unique=False)
    op.create_index(op.f('ix_report_templates_template_uuid'), 'report_templates', ['template_uuid'], unique=True)
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('search_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('search_scope', sa.String(length=20), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('sort_config', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('shared_with_team', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_uuid')
    )
    op.create_index(op.f('ix_saved_searches_id'), 'saved_searches', ['id'], unique=False)
    op.create_table('search_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('total_searches', sa.Integer(), nullable=False),
    sa.Column('unique_users', sa.Integer(), nullable=False),
    sa.Column('avg_search_duration_ms', sa.Integer(), nullable=False),
    sa.Column('popular_queries', sa.JSON(), nullable=True),
    sa.Column('popular_filters', sa.JSON(), nullable=True),
    sa.Column('popular_scopes', sa.JSON(), nullable=True),
    sa.Column('zero_result_searches', sa.Integer(), nullable=False),
    sa.Column('one_result_searches', sa.Integer(), nullable=False),
    sa.Column('multiple_result_searches', sa.Integer(), nullable=False),
    sa.Column('avg_results_per_search', sa.Integer(), nullable=False),
    sa.Column('saved_searches_created', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_analytics_id'), 'search_analytics', ['id'], unique=False)
    op.create_table('search_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('available_operators', sa.JSON(), nullable=False),
    sa.Column('default_operator', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_advanced', sa.Boolean(), nullable=False),
    sa.Column('placeholder_text', sa.String(length=255), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('filter_options', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_filters_id'), 'search_filters', ['id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('search_scope', sa.String(length=20), nullable=False),
    sa.Column('filters_used', sa.JSON(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('search_duration_ms', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('referrer_page', sa.String(length=255), nullable=True),
    sa.Column('searched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_table('search_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('search_metadata', sa.JSON(), nullable=True),
    sa.Column('search_vector', sa.Text(), nullable=True),
    sa.Column('boost_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_index_id'), 'search_index', ['id'], unique=False)
    op.create_table('search_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_text', sa.String(length=500), nullable=False),
    sa.Column('suggestion_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_suggestions_id'), 'search_suggestions', ['id'], unique=False)
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.Enum('TASK_CREATED', 'TASK_UPDATED', 'TASK_STATUS_CHANGED', 'TASK_ASSIGNED', 'TASK_OVERDUE', 'TASK_COMPLETED', 'PROJECT_CREATED', 'PROJECT_MILESTONE', 'TIME_BASED', 'USER_ACTION', 'CUSTOM_EVENT', name='triggertype'), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('condition_logic', sa.String(length=10), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', name='workflowstatus'), nullable=True),
    sa.Column('max_executions_per_day', sa.Integer(), nullable=True),
    sa.Column('execution_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_id'), 'workflow_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_is_enabled'), 'workflow_definitions', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_name'), 'workflow_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_organization_id'), 'workflow_definitions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_status'), 'workflow_definitions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_trigger_type'), 'workflow_definitions', ['trigger_type'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_workflow_uuid'), 'workflow_definitions', ['workflow_uuid'], unique=True)
    op.create_index('ix_workflows_enabled_status', 'workflow_definitions', ['is_enabled', 'status'], unique=False)
    op.create_index('ix_workflows_org_trigger', 'workflow_definitions', ['organization_id', 'trigger_type'], unique=False)
    op.create_table('workflow_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('template_config', sa.JSON(), nullable=False),
    sa.Column('required_permissions', sa.JSON(), nullable=True),
    sa.Column('is_system_template', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_templates_category'), 'workflow_templates', ['category'], unique=False)
    op.create_index('ix_workflow_templates_category_public', 'workflow_templates', ['category', 'is_public'], unique=False)
    op.create_index(op.f('ix_workflow_templates_id'), 'workflow_templates', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_templates_is_public'), 'workflow_templates', ['is_public'], unique=False)
    op.create_index(op.f('ix_workflow_templates_is_system_template'), 'workflow_templates', ['is_system_template'], unique=False)
    op.create_index(op.f('ix_workflow_templates_name'), 'workflow_templates', ['name'], unique=False)
    op.create_index(op.f('ix_workflow_templates_organization_id'), 'workflow_templates', ['organization_id'], unique=False)
    op.create_index('ix_workflow_templates_system_usage', 'workflow_templates', ['is_system_template', 'usage_count'], unique=False)
    op.create_index(op.f('ix_workflow_templates_template_uuid'), 'workflow_templates', ['template_uuid'], unique=True)
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('widget_type', sa.Enum('LINE', 'BAR', 'PIE', 'DOUGHNUT', 'AREA', 'SCATTER', 'BUBBLE', 'RADAR', 'POLAR', 'HISTOGRAM', 'HEATMAP', 'GANTT', 'BURNDOWN', 'VELOCITY', name='charttype'), nullable=False),
    sa.Column('query_config', sa.JSON(), nullable=False),
    sa.Column('chart_config', sa.JSON(), nullable=True),
    sa.Column('filter_config', sa.JSON(), nullable=True),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('refresh_interval', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('cache_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('last_data_update', sa.DateTime(), nullable=True),
    sa.Column('cached_data', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('height > 0', name='check_height_positive'),
    sa.CheckConstraint('position_x >= 0', name='check_position_x_positive'),
    sa.CheckConstraint('position_y >= 0', name='check_position_y_positive'),
    sa.CheckConstraint('width > 0', name='check_width_positive'),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_widgets_dashboard_id'), 'dashboard_widgets', ['dashboard_id'], unique=False)
    op.create_index('ix_dashboard_widgets_dashboard_order', 'dashboard_widgets', ['dashboard_id', 'display_order'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_id'), 'dashboard_widgets', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_is_visible'), 'dashboard_widgets', ['is_visible'], unique=False)
    op.create_index('ix_dashboard_widgets_org_type', 'dashboard_widgets', ['organization_id', 'widget_type'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_organization_id'), 'dashboard_widgets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_widget_type'), 'dashboard_widgets', ['widget_type'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_widget_uuid'), 'dashboard_widgets', ['widget_uuid'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('filters_applied', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('data_start_date', sa.Date(), nullable=True),
    sa.Column('data_end_date', sa.Date(), nullable=True),
    sa.Column('generation_duration_ms', sa.Integer(), nullable=True),
    sa.Column('data_points_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('shared_with_users', sa.JSON(), nullable=True),
    sa.Column('access_permissions', sa.JSON(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_data_end_date'), 'reports', ['data_end_date'], unique=False)
    op.create_index(op.f('ix_reports_data_start_date'), 'reports', ['data_start_date'], unique=False)
    op.create_index('ix_reports_date_range', 'reports', ['data_start_date', 'data_end_date'], unique=False)
    op.create_index(op.f('ix_reports_generated_at'), 'reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_is_archived'), 'reports', ['is_archived'], unique=False)
    op.create_index(op.f('ix_reports_is_public'), 'reports', ['is_public'], unique=False)
    op.create_index(op.f('ix_reports_name'), 'reports', ['name'], unique=False)
    op.create_index('ix_reports_org_generated', 'reports', ['organization_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reports_report_uuid'), 'reports', ['report_uuid'], unique=True)
    op.create_index('ix_reports_template_date', 'reports', ['template_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_reports_template_id'), 'reports', ['template_id'], unique=False)
    op.create_table('saved_search_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saved_search_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_reshare', sa.Boolean(), nullable=False),
    sa.Column('shared_by', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['saved_search_id'], ['saved_searches.id'], ),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_search_shares_id'), 'saved_search_shares', ['id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_uuid', sa.String(length=36), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('trigger_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', 'CANCELLED', name='executionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('actions_executed', sa.JSON(), nullable=True),
    sa.Column('execution_results', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_execution_uuid'), 'workflow_executions', ['execution_uuid'], unique=True)
    op.create_index(op.f('ix_workflow_executions_id'), 'workflow_executions', ['id'], unique=False)
    op.create_index('ix_workflow_executions_started_at', 'workflow_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_index('ix_workflow_executions_workflow_status', 'workflow_executions', ['workflow_id', 'status'], unique=False)
    op.create_table('report_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_uuid', sa.String(length=36), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'EXCEL', 'CSV', 'JSON', 'PNG', 'SVG', name='reportformat'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('export_settings', sa.JSON(), nullable=True),
    sa.Column('generation_duration_ms', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('exported_by', sa.Integer(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('last_downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_exports_expires', 'report_exports', ['expires_at', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_report_exports_expires_at'), 'report_exports', ['expires_at'], unique=False)
    op.create_index(op.f('ix_report_exports_export_uuid'), 'report_exports', ['export_uuid'], unique=True)
    op.create_index(op.f('ix_report_exports_exported_at'), 'report_exports', ['exported_at'], unique=False)
    op.create_index(op.f('ix_report_exports_format'), 'report_exports', ['format'], unique=False)
    op.create_index(op.f('ix_report_exports_id'), 'report_exports', ['id'], unique=False)
    op.create_index(op.f('ix_report_exports_is_deleted'), 'report_exports', ['is_deleted'], unique=False)
    op.create_index('ix_report_exports_org_format', 'report_exports', ['organization_id', 'format'], unique=False)
    op.create_index(op.f('ix_report_exports_organization_id'), 'report_exports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_report_exports_report_id'), 'report_exports', ['report_id'], unique=False)
    op.create_table('report_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('MANUAL', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='reportfrequency'), nullable=False),
    sa.Column('scheduled_time', sa.String(length=10), nullable=True),
    sa.Column('scheduled_day', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('default_filters', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('auto_export_formats', sa.JSON(), nullable=True),
    sa.Column('email_recipients', sa.JSON(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('last_failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_schedules_active_next_run', 'report_schedules', ['is_active', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_report_schedules_frequency'), 'report_schedules', ['frequency'], unique=False)
    op.create_index(op.f('ix_report_schedules_id'), 'report_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_report_schedules_is_active'), 'report_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_report_schedules_last_run_at'), 'report_schedules', ['last_run_at'], unique=False)
    op.create_index(op.f('ix_report_schedules_name'), 'report_schedules', ['name'], unique=False)
    op.create_index(op.f('ix_report_schedules_next_run_at'), 'report_schedules', ['next_run_at'], unique=False)
    op.create_index('ix_report_schedules_org_active', 'report_schedules', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_report_schedules_organization_id'), 'report_schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_report_schedules_report_id'), 'report_schedules', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_schedules_schedule_uuid'), 'report_schedules', ['schedule_uuid'], unique=True)
    op.create_index(op.f('ix_report_schedules_template_id'), 'report_schedules', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_schedules_template_id'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_schedule_uuid'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_report_id'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_organization_id'), table_name='report_schedules')
    op.drop_index('ix_report_schedules_org_active', table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_next_run_at'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_name'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_last_run_at'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_is_active'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_id'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_frequency'), table_name='report_schedules')
    op.drop_index('ix_report_schedules_active_next_run', table_name='report_schedules')
    op.drop_table('report_schedules')
    op.drop_index(op.f('ix_report_exports_report_id'), table_name='report_exports')
    op.drop_index(op.f('ix_report_exports_organization_id'), table_name='report_exports')
    op.drop_index('ix_report_exports_org_format', table_name='report_exports')
    op.drop_index(op.f('ix_report_exports_is_deleted'), table_name='report_exports')
    op.drop_index(op.f('ix_report_exports_id'), table_name='report_exports')
    op.drop_index(op.f('ix_report_exports_format'), table_name='report_exports')
    op.drop_index(op.f('ix_report_exports_exported_at'), table_name='report_exports')
    op.drop_index(op.f('ix_report_exports_export_uuid'), table_name='report_exports')
    op.drop_index(op.f('ix_report_exports_expires_at'), table_name='report_exports')
    op.drop_index('ix_report_exports_expires', table_name='report_exports')
    op.drop_table('report_exports')
    op.drop_index('ix_workflow_executions_workflow_status', table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index('ix_workflow_executions_started_at', table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_execution_uuid'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_saved_search_shares_id'), table_name='saved_search_shares')
    op.drop_table('saved_search_shares')
    op.drop_index(op.f('ix_reports_template_id'), table_name='reports')
    op.drop_index('ix_reports_template_date', table_name='reports')
    op.drop_index(op.f('ix_reports_report_uuid'), table_name='reports')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_index('ix_reports_org_generated', table_name='reports')
    op.drop_index(op.f('ix_reports_name'), table_name='reports')
    op.drop_index(op.f('ix_reports_is_public'), table_name='reports')
    op.drop_index(op.f('ix_reports_is_archived'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_generated_at'), table_name='reports')
    op.drop_index('ix_reports_date_range', table_name='reports')
    op.drop_index(op.f('ix_reports_data_start_date'), table_name='reports')
    op.drop_index(op.f('ix_reports_data_end_date'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_dashboard_widgets_widget_uuid'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_widget_type'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_organization_id'), table_name='dashboard_widgets')
    op.drop_index('ix_dashboard_widgets_org_type', table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_is_visible'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_id'), table_name='dashboard_widgets')
    op.drop_index('ix_dashboard_widgets_dashboard_order', table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_dashboard_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_index(op.f('ix_workflow_templates_template_uuid'), table_name='workflow_templates')
    op.drop_index('ix_workflow_templates_system_usage', table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_organization_id'), table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_name'), table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_is_system_template'), table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_is_public'), table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_id'), table_name='workflow_templates')
    op.drop_index('ix_workflow_templates_category_public', table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_category'), table_name='workflow_templates')
    op.drop_table('workflow_templates')
    op.drop_index('ix_workflows_org_trigger', table_name='workflow_definitions')
    op.drop_index('ix_workflows_enabled_status', table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_workflow_uuid'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_trigger_type'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_status'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_organization_id'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_name'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_is_enabled'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_id'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index(op.f('ix_search_suggestions_id'), table_name='search_suggestions')
    op.drop_table('search_suggestions')
    op.drop_index(op.f('ix_search_index_id'), table_name='search_index')
    op.drop_table('search_index')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_search_filters_id'), table_name='search_filters')
    op.drop_table('search_filters')
    op.drop_index(op.f('ix_search_analytics_id'), table_name='search_analytics')
    op.drop_table('search_analytics')
    op.drop_index(op.f('ix_saved_searches_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_report_templates_template_uuid'), table_name='report_templates')
    op.drop_index(op.f('ix_report_templates_report_type'), table_name='report_templates')
    op.drop_index('ix_report_templates_public_active', table_name='report_templates')
    op.drop_index(op.f('ix_report_templates_organization_id'), table_name='report_templates')
    op.drop_index('ix_report_templates_org_type', table_name='report_templates')
    op.drop_index(op.f('ix_report_templates_name'), table_name='report_templates')
    op.drop_index(op.f('ix_report_templates_is_system_template'), table_name='report_templates')
    op.drop_index(op.f('ix_report_templates_is_public'), table_name='report_templates')
    op.drop_index(op.f('ix_report_templates_is_active'), table_name='report_templates')
    op.drop_index(op.f('ix_report_templates_id'), table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_report_alerts_organization_id'), table_name='report_alerts')
    op.drop_index('ix_report_alerts_org_active', table_name='report_alerts')
    op.drop_index('ix_report_alerts_next_eval', table_name='report_alerts')
    op.drop_index(op.f('ix_report_alerts_name'), table_name='report_alerts')
    op.drop_index(op.f('ix_report_alerts_metric_name'), table_name='report_alerts')
    op.drop_index('ix_report_alerts_metric_active', table_name='report_alerts')
    op.drop_index(op.f('ix_report_alerts_last_triggered_at'), table_name='report_alerts')
    op.drop_index(op.f('ix_report_alerts_last_evaluated_at'), table_name='report_alerts')
    op.drop_index(op.f('ix_report_alerts_is_snoozed'), table_name='report_alerts')
    op.drop_index(op.f('ix_report_alerts_is_active'), table_name='report_alerts')
    op.drop_index(op.f('ix_report_alerts_id'), table_name='report_alerts')
    op.drop_index(op.f('ix_report_alerts_alert_uuid'), table_name='report_alerts')
    op.drop_table('report_alerts')
    op.drop_index(op.f('ix_dashboards_organization_id'), table_name='dashboards')
    op.drop_index('ix_dashboards_org_public', table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_name'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_is_system_dashboard'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_is_public'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_is_default'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_dashboard_uuid'), table_name='dashboards')
    op.drop_index('ix_dashboards_creator_default', table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_business_rules_rule_uuid'), table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_priority'), table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_organization_id'), table_name='business_rules')
    op.drop_index('ix_business_rules_org_reusable', table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_name'), table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_is_system_rule'), table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_id'), table_name='business_rules')
    op.drop_index('ix_business_rules_category_system', table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_category'), table_name='business_rules')
    op.drop_table('business_rules')
    op.drop_index(op.f('ix_automation_rules_rule_uuid'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_rule_type'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_organization_id'), table_name='automation_rules')
    op.drop_index('ix_automation_rules_org_type', table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_name'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_is_active'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_id'), table_name='automation_rules')
    op.drop_index('ix_automation_rules_active_frequency', table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_index(op.f('ix_analytics_metrics_period_start'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_period_end'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_organization_id'), table_name='analytics_metrics')
    op.drop_index('ix_analytics_metrics_org_name_period', table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_metric_uuid'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_metric_type'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_metric_name'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_is_estimated'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_id'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_entity_type'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_entity_id'), table_name='analytics_metrics')
    op.drop_index('ix_analytics_metrics_entity', table_name='analytics_metrics')
    op.drop_index('ix_analytics_metrics_category_period', table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_category'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_calculated_at'), table_name='analytics_metrics')
    op.drop_table('analytics_metrics')
    # ### end Alembic commands ###
