"""Add template system support to BaseModel and template models

Revision ID: 3b520f09a5a4
Revises: a8504512dd54
Create Date: 2025-09-23 22:45:53.313630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b520f09a5a4'
down_revision: Union[str, None] = 'a8504512dd54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
