"""Add enhanced comment system with threading, mentions, and attachments

Revision ID: 5d877179a0eb
Revises: 86c775aeab6f
Create Date: 2025-09-24 01:45:39.849732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d877179a0eb'
down_revision: Union[str, None] = '86c775aeab6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
