"""Add enhanced time tracking and task template models

Revision ID: 86c775aeab6f
Revises: 3b520f09a5a4
Create Date: 2025-09-24 01:25:53.762994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c775aeab6f'
down_revision: Union[str, None] = '3b520f09a5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
