name: Update Dependencies

on:
  schedule:
    - cron: '0 10 * * MON'  # Run every Monday at 10 AM UTC
  workflow_dispatch:

jobs:
  update-python-deps:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install pip-tools
      run: pip install pip-tools

    - name: Update requirements
      run: |
        cd backend
        # Update main requirements
        pip-compile --upgrade requirements.in --output-file requirements.txt
        # Update dev requirements  
        pip-compile --upgrade requirements-dev.in --output-file requirements-dev.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: Update Python dependencies'
        title: 'chore: Update Python dependencies'
        body: |
          This PR updates Python dependencies to their latest versions.
          
          ## Changes
          - Updated main dependencies in requirements.txt
          - Updated development dependencies in requirements-dev.txt
          
          Please review the changes and ensure all tests pass before merging.
        branch: chore/update-dependencies
        delete-branch: true

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt -r requirements-dev.txt

    - name: Run security audit
      run: |
        cd backend
        safety check --json --output safety-report.json
        
    - name: Upload security report
      uses: actions/upload-artifact@v3
      with:
        name: security-audit-report
        path: backend/safety-report.json